### ISSUE TITLE
Failed to compile with 3 errors

### ISSUE THREAD

**Issue by brizzbane** [sjquant/engster-client#1]
```

 ERROR  Failed to compile with 3 errors                                                                                                              friendly-errors 21:57:42

These dependencies were not found:                                                                                                                   friendly-errors 21:57:42
                                                                                                                                                     friendly-errors 21:57:42
* ~/components/icons/Like in ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./components/search/EnglishCard.vue?vue&type=script&lang=js&
* ~/components/icons/Pencil in ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./components/search/EnglishCard.vue?vue&type=script&lang=js&
* ~/components/icons/Share in ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./components/search/EnglishCard.vue?vue&type=script&lang=js&
                                                                                                                                                     friendly-errors 21:57:42
To install them, you can run: npm install --save ~/components/icons/Like ~/components/icons/Pencil ~/components/icons/Share 
```

First of all, I'm super newb.  I messed with Vue briefly a while ago...but for NodeJS in general, I don't know much.  I'm curious about your integration with Sanic & Gino though...so taking a look at this project.

Back to error.  I tried the suggestion:
`
npm install --save ~/components/icons/Like ~/components/icons/Pencil ~/components/icons/Share `

but that didn't work.  Can you help?

**Comment by sjquant** [comment]
Hello, @brizzbane. Thank you for commenting issue. 
this is frontend part of my project using Vue.js.
If you want to know about sanic and gino integration, please look at [this project](https://github.com/sjquant/engster-server).
In addition, I am working on this project, and it is at initial stage.

And if you want to check this frontend part, you can run with command `yarn dev`

**Comment by brizzbane** [comment]
I know this is the frontend part.  I was just commenting that I started looking at this project after seeing your sanic/gino project.  (I have looked for good examples of integration w/Sanic in the past...).  Sorry that comment was just confusing ... and not about this issue.

I think maybe the errors are from this file:

https://github.com/sjquant/engster-client/blob/master/components/search/EnglishCard.vue

Line 36-39, I think they should be like line 35?

`import LineCard from "../common/LineCard.vue";`

instead of:

`import Tag from "~/components/common/Tag.vue";`

I'm guessing it should be:

`import Tag from "../components/common/Tag.vue";`

I will try that and see if it fixes..  Anyways, thanks for the reply.

**Comment by sjquant** [comment]
Okay, I misunderstood. I used [nuxt](https://nuxtjs.org/) framework for server-side rendering in vue. In `nuxt` **~** indicates **src** directory. I think you might not install `nuxt`. Have you installed all dependencies in package.json? If not, you can install them just with `npm install` or `yarn install`(if you use yarn) command.

**Comment by brizzbane** [comment]
I found out what the problem was...(at least for me).

`import Pencil from "~/components/icons/Pencil";`

had to be changed to:

`import Pencil from "~/components/Icons/Pencil";`

(Capital I).  Then it compiled/started without errors for me. (After also editing Like and Share in addition to Pencil)

**Comment by sjquant** [comment]
Oh, icons directory uploaded to github with capital I.
I found it now. Thanks for reporting.
